### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Repwoc** [KurtE/ADCL_t4#7]
I had to modify the ADCL_Module_t4.h file to get it to compile.  Specifically I added static_cast() functions in lines 29 and 30 to cast the enum values to the underlying type:

enum class ADC_REFERENCE : uint8_t {
    REF_3V3 = static_cast<uint8_t>(ADC_REF_SOURCE::REF_DEFAULT), /*!< 3.3 volts */
    NONE = static_cast<uint8_t>(ADC_REF_SOURCE::REF_NONE) // internal, do not use
};

**Comment by KurtE** [comment]
Sorry, I should mention and close this library out, as most of work was added into the official ADCL library and as such
we have not touched this library in a long time...

**Comment by KurtE** [comment]
I am going to make this project as archived
